### ISSUE TITLE
Error occurred while enabling ChessCraft v0.5.0 

### ISSUE THREAD

**Issue by mmahdi-sz** [jpenilla/chesscraft#87]
i run last version of chesscraft in purpur 1.20.1 

[06:07:59 ERROR]: Error occurred while enabling ChessCraft v0.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/TranslationArgument
        at xyz.jpenilla.chesscraft.dependency.net.kyori.adventure.serializer.configurate4.ConfigurateComponentSerializerImpl.makeSerializers(ConfigurateComponentSerializerImpl.java:102) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.dependency.net.kyori.adventure.serializer.configurate4.ConfigurateComponentSerializerImpl.<init>(ConfigurateComponentSerializerImpl.java:59) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.dependency.net.kyori.adventure.serializer.configurate4.ConfigurateComponentSerializerImpl.<init>(ConfigurateComponentSerializerImpl.java:49) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.dependency.net.kyori.adventure.serializer.configurate4.ConfigurateComponentSerializerImpl$Builder.build(ConfigurateComponentSerializerImpl.java:139) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.dependency.net.kyori.adventure.serializer.configurate4.ConfigurateComponentSerializerImpl.<clinit>(ConfigurateComponentSerializerImpl.java:50) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.dependency.net.kyori.adventure.serializer.configurate4.ConfigurateComponentSerializer.configurate(ConfigurateComponentSerializer.java:53) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.config.ConfigHelper.lambda$createLoader$0(ConfigHelper.java:46) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.dependency.org.spongepowered.configurate.ConfigurationOptions.serializers(ConfigurationOptions.java:165) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.config.ConfigHelper.lambda$createLoader$1(ConfigHelper.java:39) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.dependency.org.spongepowered.configurate.loader.AbstractConfigurationLoader$Builder.defaultOptions(AbstractConfigurationLoader.java:428) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.config.ConfigHelper.createLoader(ConfigHelper.java:39) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.config.ConfigHelper.saveConfig(ConfigHelper.java:95) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.config.ConfigHelper.saveConfig(ConfigHelper.java:88) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.ChessCraft.saveConfig(ChessCraft.java:86) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.ChessCraft.reloadMainConfig(ChessCraft.java:78) ~[chesscraft-0.5.0-all.jar:?]
        at xyz.jpenilla.chesscraft.ChessCraft.onEnable(ChessCraft.java:40) ~[chesscraft-0.5.0-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.TranslationArgument
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 28 more

**Comment by jpenilla** [comment]
The next update will drop support for outdated versions https://github.com/jpenilla/chesscraft/commit/fc8572bb9b24d498870189357223086df4ac4f08
